# Generated by Django 6.0.2 on 2026-02-22 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LangLens', '0002_vocabulary'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocabulary',
            name='icon_name',
            field=models.CharField(db_default='fa-solid fa-building-circle-xmark', help_text='FontAwesome icon name (e.g., fa-utensils)', max_length=50),
        ),
    ]
