# Generated by Django 6.0.2 on 2026-02-28 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LangLens', '0003_vocabulary_icon_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingmodule',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, unique=True),
        ),
        migrations.AddField(
            model_name='readingmodule',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, unique=True),
        ),
    ]
