# Generated by Django 6.0.2 on 2026-03-02 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LangLens', '0004_listingmodule_slug_readingmodule_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listingmodule',
            name='correct_list_items',
        ),
        migrations.RemoveField(
            model_name='listingmodule',
            name='text_for_audio',
        ),
        migrations.AddField(
            model_name='listingmodule',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='listening_mode/'),
        ),
        migrations.AddField(
            model_name='vocabulary',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
