# Generated by Django 6.0.2 on 2026-03-06 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LangLens', '0005_remove_listingmodule_correct_list_items_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocabulary',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='Audio_reading/Vocabulary/'),
        ),
    ]
