# Generated by Django 6.0.2 on 2026-03-06 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LangLens', '0006_vocabulary_audio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingmodule',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='Audio_reading/listening_mode/'),
        ),
    ]
