# Generated by Django 6.0.2 on 2026-03-07 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LangLens', '0007_alter_listingmodule_audio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vocabulary',
            name='icon_name',
        ),
        migrations.AlterField(
            model_name='listingmodule',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='audio/listening_mode/'),
        ),
        migrations.AlterField(
            model_name='vocabulary',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='audio/vocabulary_audio/'),
        ),
    ]
