# Generated by Django 6.0.2 on 2026-03-07 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LangLens', '0008_remove_vocabulary_icon_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocabulary',
            name='icon_name',
            field=models.CharField(db_default='fa-solid fa-building-circle-xmark', help_text='FontAwesome icon name (e.g., fa-utensils)', max_length=50),
        ),
        migrations.AlterField(
            model_name='listingmodule',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='Audio_reading/listening_mode/'),
        ),
        migrations.AlterField(
            model_name='vocabulary',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='Audio_reading/Vocabulary/'),
        ),
    ]
