# Generated by Django 6.0.2 on 2026-03-17 02:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LangLens', '0009_vocabulary_icon_name_alter_listingmodule_audio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='writingproject',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='writingproject',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
