# Generated by Django 6.0.2 on 2026-03-17 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LangLens', '0010_writingproject_created_at_writingproject_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='writingproject',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='writingproject',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='draft', max_length=16),
        ),
        migrations.AddField(
            model_name='writingproject',
            name='word_goal',
            field=models.PositiveIntegerField(default=500),
        ),
    ]
