# Generated by Django 6.0.2 on 2026-04-14 04:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LangLens', '0012_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uservocabulary',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='uservocabulary',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uservocabulary',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='uservocabulary',
            name='reading_module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_words', to='LangLens.readingmodule'),
        ),
        migrations.AlterField(
            model_name='uservocabulary',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_words', to=settings.AUTH_USER_MODEL),
        ),
    ]
