# Generated by Django 6.0.2 on 2026-04-14 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LangLens', '0013_alter_uservocabulary_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingmodule',
            name='story_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
